### ISSUE TITLE
If the tray app doesn't launch (Jellyfin 10.5.5 and lower)

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-server-windows#27]
There is a .NET and Windows issue with self-extracting executables. This will be resolved in Jellyfin 10.6+. If you are using an older version, here are the steps to fix your tray app temporarily.

1. Open File Explorer and go to `%temp%\.net`
2. Find the folder with the name “JellyfinTray.____” (it will have a mix of letters and numbers)
3. Delete this folder
4. Try running the tray app again

_Originally posted by @anthonylavado in https://github.com/jellyfin/jellyfin-server-windows/issues/18#issuecomment-562814135_

**Comment by dkanada** [comment]
Is it resolved in the current source? I haven't kept track of this issue.

**Comment by anthonylavado** [comment]
@dkanada I haven't pushed the fix yet. This is part of a cleanup to consolidate all information.

**Comment by nielsvanvelzen** [comment]
When the tray app doesn't exist (Windows shows a dialog that it is missing) you can try the following steps:
- Download the installer for your current version (should be the latest, at this moment 10.6.4)
- Run the installer
  - The installer should tell it's going to upgrade, if it doesn't your data is corrupt and the installer _might_ overwrite your current data folders
- Start the tray app again

Do not use the .exe from the releases page since it's outdated and doesn't work.
