### ISSUE TITLE
[Issue]: Black screen when I launch Jellyfin

### ISSUE THREAD

**Issue by luckyluke985** [jellyfin/jellyfin-server-windows#89]
When I tried to launch Jellyfin today a black screen (with a dark gray bar on top) showed up in Firefox. When I right-click on the tray app in the task bar the options ‘Stop Jellyfin’ and ‘Open Jellyfin’ are grayed out. I’m no expert and have no Idea what to do. If anyone could help me, thanks in advance. If anyone could help me thanks in advance!

### Jellyfin Version

10.8.10

### Environment

```markdown
- OS:Windows
- Browser: Firefox
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage: Samsung SSD 870 QVO 1TB
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by likwid101** [comment]
Having the same problem with the black screen and grey bar at the top... However, when I go to a private browser it works just fine. This is happening on Firefox. I tried to clear the cookies but didn't fix anything. Other browsers on my computer work just fine. So, has to do something with FF I'm guessing. Any things to try? Happening on my Andriod FF as well

**Comment by anthonylavado** [comment]
Sorry to have gotten to this too late for everyone. Usually clearing cookies isn't enough. You'd want to "Clear Website Data". There are different ways to do this depending on browser, and you only need to do it for the URL/Address you're using for Jellyfin.

This is because some of the settings/information are kept in HTML5 Local Storage, not in traditional cookies.
